replicaCount: 1

image:
  tag: "1.0.0"

service:
  type: NodePort
  port: 9001

resources:
  limits:
    cpu: 600m
    memory: 600Mi

  requests:
    cpu: 100m
    memory: 256Mi


ingress:
  enabled: true
  className: nginx
  host: demo-api.local
  path: /demo


autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60